version: "3.3"
services:
  app1:
    container_name: app1
    image: hellostranger:latest
    ports:
    - "5000:5000"
    volumes:
    - type: bind
      source: ./elk/logs 
      target: /home/salmen/logs
  app2:
    container_name: app2
    image: hellostranger:latest
    ports:
    - "5001:5000"
    volumes:
    - type: bind
      source: ./elk/logs
      target: /home/salmen/logs
