version: "3.3"
services:
  app1:
    image: hellostranger:latest
    ports:
    - "5000:5000"
    volumes:
    - type: bind
      source:  
      target: /home/salmen/logs
  app2:
    image: hellostranger:latest
    ports:
    - "5001:5000"
    volumes:
    - type: bind
      source: 
      target: /home/salmen/logs
