version: "3.3"
services:
  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
    - cluster.name=es-standalone
    - node.name=es
    - bootstrap.memory_lock=true
    - discovery.seed_hosts=es
    - cluster.initial_master_nodes=es
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - type: bind
      source: ./es-vol
      target: /usr/share/elasticsearch/data
    networks:
    - elastic
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
    - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: '["http://es:9200"]'
    depends_on: 
    - es
    networks:
    - elastic
  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit:1.5
    environment:
      FLUENT_ELASTICSEARCH_HOST: es
      FLUENT_ELASTICSEARCH_PORT: 9200
    ports:
    - "2020:2020"
    volumes:
    - type: bind
      source: ./logs
      target: /var/log
    - type: bind
      source: ./fluent-config
      target: /fluent-bit/etc
    networks:
    - elastic
    depends_on:
    - kibana

volumes:
  es-data:
    driver: local

networks:
  elastic:
    driver: bridge
